# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
    GREETING: smarthomeEndpoint
    IMAGE_VERSION: v3

tasks:
    default:
        desc: Print a greeting message
        cmds:
            - echo "Taskfile for {{.GREETING}}"
            - echo "    Usage - task <taskname>"
            - echo "    Valid tasks - build, create-image, down, run, cleanall"
        silent: true

    build:
        cmds:
            - mvn clean package -Dnative
        silent: true
    
    create-image:
        cmds:
            - podman build -t domenicopiol/smarthome-endpoint:{{.IMAGE_VERSION}} .
            - podman tag domenicopiol/smarthome-endpoint:{{.IMAGE_VERSION}} domenicopiol/smarthome-endpoint:latest
        silent: true
    
    down:
        cmds:
            - podman compose -f compose.yaml down
            - echo
            - podman ps
        silent: true
            
    run:
        cmds:
            - podman compose -f compose.yaml up -d
            - echo
            - podman ps -a
        silent: true
    
    cleanall:
        cmds:
            - podman rmi --all