# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
    GREETING: smarthomeEndpoint
    IMAGE_VERSION: v3
    ILOPWD: '{{.ILOPWD | default "MYILOPASSWD"}}'

tasks:
    default:
        desc: Print a greeting message
        cmds:
            - echo "Taskfile for {{.GREETING}}"
            - echo "    Usage - task <taskname> [ILOPWD=<your ilopwd>]"
        silent: true
    
    create-image:
        cmds:
            - podman build -t domenicopiol/smarthome-endpoint:{{.IMAGE_VERSION}} .
            - podman tag domenicopiol/smarthome-endpoint:{{.IMAGE_VERSION}} domenicopiol/smarthome-endpoint:latest
        silent: true
    
    stop:
        cmds:
#            - podman compose -f compose.yaml down  
            - podman compose -f compose.yaml up -d
            - echo
            - podman ps
        silent: true
            
    run:
        cmds:
 #           - podman run -d --rm --name smarthome-endpoint --network host -e smarthome.wakeup.endpoints='HEARTOFGOLD=08:BF:B8:01:33:17,IMAC=10:DD:B1:BD:FE:C2' -e smarthome.homelab.ilopwd='{{.ILOPWD}}' domenicopiol/smarthome-endpoint:{{.IMAGE_VERSION}}
            - podman compose -f compose.yaml down
            - echo
            - podman ps -a
        silent: true
    
    cleanall:
        cmds:
            - podman rmi --all